### ISSUE TITLE
error reading changelog: changelog file does not contain version 

### ISSUE THREAD

**Issue by AsafMah** [anton-yurchenko/git-release#106]
### Description
Can't release a version since the parser claims it can't find the version in the config file.
Previous versions worked, and the new one is clearly there.

### Tag
v.5.0.2

### Workflow
[```Attach your GitHub Action Workflow YAML```
](https://github.com/Azure/azure-kusto-java/blob/master/.github/workflows/release.yml)

### Changelog
[```Attach a full changelog```  
](https://github.com/Azure/azure-kusto-java/blob/master/CHANGELOG.md)

### Log
[```Attach an execution log```](https://github.com/Azure/azure-kusto-java/actions/runs/5985308566/job/16237270942)
https://github.com/Azure/azure-kusto-java/actions/runs/5985376582

**Comment by anton-yurchenko** [comment]
Hello @AsafMah,
You have a typo on the last three releases in your changelog file.
I have raised you a PR that is supposed to fix the problem: https://github.com/Azure/azure-kusto-java/pull/322
