### ISSUE TITLE
Allow taking the latest changelog version instead of using TAG_PREFIX_REGEX

### ISSUE THREAD

**Issue by davebarda** [anton-yurchenko/git-release#126]
### Description
In release candidate branches, we're having a suffix with the commit name (as we release version to test our code by some branch naming convention and we don' want conflicts on every push), I find it useful to just take the latest version in the changelog instead of searching for the specific version - which couldn't be used in my case, as it depends on the commit hash which is unknown.

**Comment by anton-yurchenko** [comment]
I think the [Unreleased](https://keepachangelog.com/en/1.0.0/#effort) section of the changelog might be useful here.

Here is a [configuration](https://github.com/anton-yurchenko/git-release/blob/main/docs/example.md#unreleased) that you may use to maintain single release and update it with each execution of the action.
