### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by Wolf2323** [anton-yurchenko/git-release#75]
### Description
We created a new release, but during the upload of the artifacts there was an issue. It says that the artifacts where not uploaded, but the are actually uploaded successfully. I am not sure it this is a bug, but may it should be checked. If you think there is nothings suspicious, you can simply close this.

### Tag
`v1.12.9`

### Workflow
https://github.com/BetonQuest/BetonQuest/blob/master/.github/workflows/build.yml

### Changelog
https://github.com/BetonQuest/BetonQuest/blob/master_v1.12/CHANGELOG.md

### Log
https://github.com/BetonQuest/BetonQuest/runs/7001487096?check_suite_focus=true

### Screenshots
![image](https://user-images.githubusercontent.com/4036106/175003112-abe7b1e8-c6fb-44d0-9a22-2cb880b30227.png)

**Comment by anton-yurchenko** [comment]
Hello @Wolf2323, thanks again for your contribution.

Weird, you actually had your connection terminated during an upload. It seems that it happened during the final stages when an actual file transfer should have been completed.

There are multiple reasons I don't want to start digging into that problem:

1. I believe that this is a specific edge case (happened in 1/38,000 executions, according to issue reports)
2. Impossible to recreate
3. Action behavior is correct, it has encountered an error and cannot guarantee a file upload
4. It is safer to fail the build, so the maintainer can manually check the end result

If more people will encounter that problem, I will surely re-open this issue and invest time in it.

Closing this as "declined" for now.
Thanks again!

**Comment by Wolf2323** [comment]
Thanks, that was what i thought. Better report it for statistic and may some day it helps other people ;)
