### ISSUE TITLE
Automate adding a footer to the release note

### ISSUE THREAD

**Issue by rgriebl** [anton-yurchenko/git-release#82]
Taking the release message from the CHANGELOG.md is a great way to automate releases, but I still have to manually amend each new release note with a "Please have a look (link here) for the installation instructions". (and this doesn't belong in the changelog).
It would be nice to have a new option (like e.g. `RELEASE_NOTE_APPEND="<string that gets appended to the changelog md>"` to automate this workflow.

**Comment by anton-yurchenko** [comment]
Hello @rgriebl,
[git-release](https://github.com/anton-yurchenko/git-release) relies on a [go-changelog](https://github.com/anton-yurchenko/go-changelog) package which supports: [Keep a Changelog](https://keepachangelog.com/) and [Common Changelog](https://common-changelog.org/).

If you look into [Common Changelog - Notice](https://common-changelog.org/#23-notice) documentation, you will see that you might just add free text at the beginning of each version, like:
```
## [1.8.0-rc.1] - 2021-01-02

**This is a notification area**
Please use this to add more context to the release
    ```
      There are breaking changes in this release
    ```

### Added

- A feature here
- Another one here

### Fixed

- Nasty Bug
```

[git-release](https://github.com/anton-yurchenko/git-release) will publish a release like this:
<img width="935" alt="image" src="https://user-images.githubusercontent.com/33016810/192737956-f3882f25-ec8f-4204-9c68-f1a432661912.png">
