### ISSUE TITLE
SIGSEGV on v5 when no changes for a version (Unreleased)

### ISSUE THREAD

**Issue by tajobe** [anton-yurchenko/git-release#86]
### Description
When attempting to create a release with no changes, the git-release action panics with a SIGSEGV.

This might seem like an unusual thing to do, but it is an artifact of CI on commit, where my intention is to always produce a latest `Unreleased` snapshot for any commit to master. Some commits may be non-functional and further this makes a workflow immediately following a tagged release fail every time. 

### Tag
`v5.0.0`

### Workflow
https://github.com/dotRun/MCVotifierLib/blob/master/.github/workflows/publish-workflow.yml

### Changelog
https://github.com/dotRun/MCVotifierLib/blob/ea11c2a594d8fa63f8b931dc996ba0ec6fc57048/CHANGELOG.md

### Log
```
 DEBUG git-release v5.0.0                           
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x65dcae]

goroutine 1 [running]:
github.com/anton-yurchenko/go-changelog.(*Changes).ToString(0x0)
	/go/pkg/mod/github.com/anton-yurchenko/go-changelog@v1.0.4/changes.go:24 +0x2e
main.(*Configuration).GetChangelog(0xc00005c360, {0x75d400?, 0x91e9d0}, 0xc00007c240)
	/opt/src/config.go:106 +0xe5
main.main()
	/opt/src/main.go:71 +0x1e9
```

**Comment by anton-yurchenko** [comment]
Thanks @tajobe, a fix was released on [v5.0.1](https://github.com/anton-yurchenko/git-release/releases/tag/v5.0.1)
